version: '2'

services:
  redis:
    container_name: api_redis
    image: 'redis'
    command: redis-server --appendonly yes
    volumes:
      - 'redis:/data'
    ports:
      - "6379:6379"

  website:
    container_name: api_server
    depends_on:
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'

volumes:
  redis: