default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  port: 3306
  database: deals_qa
  username: "root"
  password: ""
  host: 127.0.0.1

test:
  <<: *default
  database: deals_qa
  username: "root"
  password: ""
  host: 127.0.0.1

production:
  <<: *default
  username: "root"
  password: ""
  charset: utf8
  collation: utf8_bin
  port: 3306
  database: deals_qa
  host: 127.0.0.1
